name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Kubernetes
        uses: azure/setup-kubernetes@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Deploy with Helm
        run: helm upgrade --install mon-app ./mon-app